### PR TITLE
vertically adjust github icons

### LINKED ISSUE #28: vertical-align
Icons are not properly aligned vertically in GitHub.
I suggest adding `vertical-align: -3px;` to the `` tags.

default | + github-vscode-icons | + vertical-align
-------|------------------------|----------------
Capture d’écran 2020-08-26 à 12 30 52 | Capture d’écran 2020-08-26 à 12 29 52 | Capture d’écran 2020-08-26 à 12 34 25

What do you think?

### PR DESCRIPTION
**Pull request by antoinerousseau**
Fixes #28 

Tested OK on GitHub with Chrome 85.

### CODE REVIEW

**Comment by s-weigand** [comment]
To me `vertical-align: middle;` and `vertical-align: -2px;` look exactly the same.
Can you confirm this?

**Comment by antoinerousseau** [comment]
@s-weigand nope, there is a 2 pixels difference for me (`middle` looks like `-4px` in my case...)

**Comment by s-weigand** [comment]
Ohh looks like Firefox allows me to change values in the injected script, but doesn't apply the changes.
While chome doesn't allow the changes at all.

**Comment by antoinerousseau** [comment]
Yeah... you can add it as an inline `style` on one icon just to see the difference.
I loaded the `build` folder as a Chrome extension and hit the extension reload button when changing code.

**Comment by s-weigand** [comment]
Anyway, since I'm just a fellow contributor and it looks like @dderevjanik didn't have much time for this extension in the last months, my suggestion would be to ask @kidonng to implement adding the class `vscode-icon` in #27.That way we can prevent the trouble of having a merge conflict when @dderevjanik has time again ^^

**Comment by dderevjanik** [comment]
guys, sorry for a lot of inactivity recently. 
finally I managed to have a time and look over all PRs and issues again.

Just asking, is this already included in #27 ? So we can close this one ?

**Comment by kidonng** [comment]
> Just asking, is this already included in #27 ? So we can close this one ?

The size has been adjusted to the same size as GitHub's: https://github.com/dderevjanik/github-vscode-icons/pull/27/files#diff-ff6b47a1ca1f34dcc3c93132786338318f688c8b1277ec6776d08ad181e11a55R97
But the `.vscode-icon` class is not included. I didn't remember seeing anything different without the class, so correct me if I'm wrong.

**Comment by antoinerousseau** [comment]
The missing class does make a visible difference, as shown in https://github.com/dderevjanik/github-vscode-icons/issues/28, thus this PR.

**Comment by dderevjanik** [comment]
@antoinerousseau can I close this one and merge #27  ?

**Comment by antoinerousseau** [comment]
@dderevjanik I just tried #27 locally by building it and loading it into Chrome and the problem is the same.
I think you can merge #27 and then I'll update my PR.

**Comment by antoinerousseau** [comment]
@dderevjanik I've updated and tested my PR :)

**Comment by dderevjanik** [comment]
@antoinerousseau thanks ! It looks much better now :)

**Pull request merged**
